application: sfenreader
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(html|ico|css|js|ttf|js|swf))
  static_files: htdocs/\1
  upload: htdocs/

- url: /(static_img\/.*\.(png|gif))
  static_files: htdocs/\1
  upload: htdocs/

- url: /
  static_files: htdocs/index.html
  upload: htdocs/

- url: /sfen
  script: sfen.py

- url: /sfen_dev
  script: sfen_dev.py

- url: /sfen_test
  script: sfen_test.py

- url: /.*
  script: not_found.py

libraries:
- name: PIL
  version: latest
