application: sfenreader
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(html|ico|css|js|ttf|js|swf))
  static_files: htdocs/\1
  upload: htdocs/

- url: /(static_img\/.*\.(png|gif))
  static_files: htdocs/\1
  upload: htdocs/

- url: /
  static_files: htdocs/index.html
  upload: htdocs/

- url: /sfen
  script: sfen.py

- url: /.*
  script: not_found.py
